export default {
  '@primary-color': '#FF6F61',
  '@success-color': '#389E0D',
  '@info-color': '#018BE0',
  '@warning-color': '#FA8C16',
  '@error-color': '#CF1322',
  '@highlight-color': '#FF8C81',
  '@body-background': '#ffffff',
  '@layout-body-background': '#fbfbfb',
  '@layout-header-background': '#333',
  '@font-size-base': '14px',
  '@border-radius-base': '2px',
  '@border-radius-sm': '1px',
  '@form-item-margin-bottom': '16px',
  '@progress-radius': '1px',
  '@table-row-hover-bg': '#fafafa',
  '@table-padding-vertical': '14px',
  '@tabs-card-tab-active-border-top': '2px solid @primary-color',
  '@switch-color': '@info-color',
  '@wave-animation-width': '5px',
}
