export default {
  '@primary-color': '#0066ff',
  '@success-color': '#2fb856',
  '@info-color': '#0070cc',
  '@warning-color': '#ffa000',
  '@error-color': '#d31111',
  '@highlight-color': '#fb4c4c',
  '@body-background': '#ffffff',
  '@layout-body-background': '#f5f5f5',
  '@layout-header-background': '#222222',
  '@font-size-base': '12px',
  '@border-radius-base': '1px',
  '@border-radius-sm': '1px',
  '@form-item-margin-bottom': '16px',
  '@progress-radius': '1px',
  '@table-row-hover-bg': '#fafafa',
  '@table-padding-vertical': '14px',
  '@tabs-card-tab-active-border-top': '2px solid @primary-color',
  '@switch-color': '@success-color',
  '@wave-animation-width': '5px',
  '@alert-success-border-color': "~`colorPalette('@{success-color}', 1) `",
  '@alert-info-border-color': "~`colorPalette('@{info-color}', 1) `",
  '@alert-warning-border-color': "~`colorPalette('@{warning-color}', 1) `",
  '@alert-error-border-color': "~`colorPalette('@{error-color}', 1) `",
};
